---
- hosts: docker
  become: yes

  tasks:
    - name: Add Docker Repository
      yum_repository:
        name: docker
        description: Centos7 Docker Repository
        baseurl: https://yum.dockerproject.org/repo/main/centos/7
        enabled: yes
        gpgcheck: no

    - name: Install Docker Engine
      yum:
        name: docker-engine-17.05.0.ce-1.el7.centos
        state: present

    - name: Install PIP Modules
      pip:
        name: docker-py docker-compose
