---
- hosts: docker
  become: yes

  tasks:
    - name: Install Docker
      yum: name={{ item }} state=present
      with_items:
        - docker
        - docker-python
        - docker-unit-test

    - name: Install PIP Modules
      pip:
        name: docker-py docker-compose
