---
- hosts: centos
  become: yes

  tasks:
    - name: Install Python
      yum: name={{ item }} state=present
      with_items:
        - python
        - python-devel
        - python-setuptools

    - name: Install PIP
      easy_install:
        name: pip
        state: present

    - name: Install Python Libraries with PIP
      pip:
        name: NumPy, SciPy, ansible, apache-libcloud, matplotlib
