---
- hosts: centos
  tags: centos_base
  become: yes

  tasks:
  - name: Install Dev Tools
    yum: name={{ item }} state=present
    with_items:
        - gcc
        - gcc-c++
        - kernel-headers

- hosts: ubuntu
  tags: ubuntu_base
  become: yes

  tasks:
    - name: Install Dev Tools
      apt: name={{ item }} state=present
      with_items:
        -  openjdk-11-jdk
        -  sqlite3
        -  libsqlite3-dev
        -  ant
        -  r-base-core
        -  python-pyodbc
