---
- hosts: centos
  become: yes

  tasks:
    - name: Install Dev Tools
      yum: name={{ item }} state=present
      with_items:
        - gcc
        - gcc-c++
        - kernel-headers

- hosts: ubuntu
  become: yes

  tasks:
    - name: Install Dev Tools
      apt: name={{ item }} state=present
      with_items:
        -  openjdk-9-jre-headless
