---
- hosts: krueger
  become: yes

  tasks:
    - name: Install Apache.
      yum: name={{ item }} state=present
      with_items:
        - httpd
        - httpd-devel

      - name: Enable Apache.
        service: name=httpd state=started enabled=yes
